export const GOT_ALL_CAMPUSES = "GOT_ALL_CAMPUSES";
export const ADDED_NEW_CAMPUS = "ADDED_NEW_CAMPUS";
export const GOT_SINGLE_CAMPUS = "GOT_SINGLE_CAMPUS";

export const GOT_ALL_STUDENTS = "GOT_ALL_STUDENTS"
export const GOT_ONE_STUDENT = "GOT_ONE_STUDENT"
export const ADDED_NEW_STUDENT = "ADDED_NEW_STUDENT";
