export const GOT_ALL_CAMPUSES = "GOT_ALL_CAMPUSES";
export const ADDED_NEW_CAMPUS = "ADDED_NEW_CAMPUS";
export const GOT_SINGLE_CAMPUS = "GOT_SINGLE_CAMPUS";
export const DELETED_CAMPUS = "DELETED_CAMPUS";
export const UPDATED_CAMPUS = "UPDATED_CAMPUS";

export const GOT_ALL_STUDENTS = "GOT_ALL_STUDENTS";
export const ADDED_NEW_STUDENT = "ADDED_NEW_STUDENT";
export const GOT_SINGLE_STUDENT = "GOT_SINGLE_STUDENT";
export const DELETED_STUDENT = "DELETED_STUDENT";
export const UPDATED_STUDENT = "UPDATED_STUDENT";
